import dashboard, google_forms, config
pages = dashboard.load_pages()
forms = google_forms.load_google_form_indexes(config)
df = dashboard.pages_to_df(pages, forms)
pros = df[df['Source']=='New Prospects'].copy()
print('TOTAL', len(df), 'PROSPECTS', len(pros))
print('PIPELINE_COUNTS')
print(pros['Pipeline Stage'].value_counts(dropna=False).to_string())
print('\nALL_FORMS_SUBMITTED')
print(pros['All Forms Submitted'].value_counts(dropna=False).to_string())
print('\nNEEDS_ASSESSMENT')
print(pros['Needs Assessment'].value_counts(dropna=False).to_string())
print('\nSTATUS_TOP')
print(pros['Status'].value_counts(dropna=False).head(20).to_string())
